# Generated by Django 5.2.8 on 2025-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('course_interest', models.CharField(blank=True, max_length=200, verbose_name='Интересующий курс')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
            ],
            options={
                'verbose_name': 'Course Application',
                'verbose_name_plural': 'Course Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('lms', 'LMS Mode - Full Learning Platform'), ('applications', 'Applications Mode - Pre-registration Landing Page')], default='lms', help_text='Select the platform operation mode', max_length=20, verbose_name='Platform Mode')),
                ('landing_page_title', models.CharField(default='Скоро открытие!', max_length=200, verbose_name='Landing Page Title')),
                ('landing_page_description', models.TextField(default='Мы готовим для вас лучшую платформу для обучения. Оставьте заявку, и мы уведомим вас о старте.', verbose_name='Landing Page Description')),
                ('application_form_enabled', models.BooleanField(default=True, verbose_name='Enable Application Form')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
